In [2]:
import os
import pandas as pd

# ============================================================
# FINAL PROJECT QA CHECK
# ============================================================

required_files = {
    "Cleaned NAV": r"D:\mutual-fund-analysis\data\processed\nav_history_cleaned.csv",
    "Fund Scorecard": r"fund_scorecard.csv",
    "Tracking Error": r"tracking_error_comparison.csv",
    "Benchmark Summary": r"benchmark_summary.csv",
    "Rolling Tracking Difference": r"rolling_30d_tracking_difference.csv",
    "Normalized Performance": r"normalized_benchmark_performance.csv",
}

print("=" * 60)
print("FINAL PROJECT QA CHECK")
print("=" * 60)

for name, path in required_files.items():

    if os.path.exists(path):

        df = pd.read_csv(path)

        print(f"✅ {name}")
        print(f"   File: {path}")
        print(f"   Rows: {len(df):,}")
        print(f"   Columns: {len(df.columns)}")

    else:
        print(f"❌ {name}")
        print(f"   Missing: {path}")

    print("-" * 60)

============================================================
FINAL PROJECT QA CHECK
============================================================
✅ Cleaned NAV
   File: D:\mutual-fund-analysis\data\processed\nav_history_cleaned.csv
   Rows: 46,000
   Columns: 3
------------------------------------------------------------
✅ Fund Scorecard
   File: fund_scorecard.csv
   Rows: 40
   Columns: 15
------------------------------------------------------------
✅ Tracking Error
   File: tracking_error_comparison.csv
   Rows: 5
   Columns: 6
------------------------------------------------------------
✅ Benchmark Summary
   File: benchmark_summary.csv
   Rows: 5
   Columns: 8
------------------------------------------------------------
✅ Rolling Tracking Difference
   File: rolling_30d_tracking_difference.csv
   Rows: 11,500
   Columns: 5
------------------------------------------------------------
✅ Normalized Performance
   File: normalized_benchmark_performance.csv
   Rows: 8,050
   Columns: 5
------------------------------------------------------------

In [3]:
scorecard = pd.read_csv("fund_scorecard.csv")

print("Scorecard shape:", scorecard.shape)

print("\nColumns:")
print(scorecard.columns.tolist())

print("\nDuplicate AMFI codes:",
      scorecard["amfi_code"].duplicated().sum())

print("\nMissing values:")
print(scorecard.isna().sum())

print("\nTop 5 Funds:")
display(
    scorecard
    .sort_values("Overall_Rank")
    .head(5)
)

Scorecard shape: (40, 15)

Columns:
['amfi_code', 'scheme_name', 'CAGR_3Y_pct', 'Return_Rank', 'Sharpe_Rank', 'Alpha_Rank', 'Expense_Rank', 'MDD_Rank', 'Return_Score', 'Sharpe_Score', 'Alpha_Score', 'Expense_Score', 'MDD_Score', 'Fund_Score', 'Overall_Rank']

Duplicate AMFI codes: 0

Missing values:
amfi_code        0
scheme_name      0
CAGR_3Y_pct      0
Return_Rank      0
Sharpe_Rank      0
Alpha_Rank       0
Expense_Rank     0
MDD_Rank         0
Return_Score     0
Sharpe_Score     0
Alpha_Score      0
Expense_Score    0
MDD_Score        0
Fund_Score       0
Overall_Rank     0
dtype: int64

Top 5 Funds:

,amfi_code,scheme_name,CAGR_3Y_pct,Return_Rank,Sharpe_Rank,Alpha_Rank,Expense_Rank,MDD_Rank,Return_Score,Sharpe_Score,Alpha_Score,Expense_Score,MDD_Score,Fund_Score,Overall_Rank
0,148567,Mirae Asset Large Cap Fund - Regular - Growth,34.000916,2.0,7.0,10.0,20.0,8.0,97.435897,84.615385,76.923077,51.282051,82.051282,81.666667,1
1,120843,Kotak Flexicap Fund - Regular - Growth,29.582770,7.0,10.0,3.0,19.0,13.0,84.615385,76.923077,94.871795,53.846154,69.230769,78.589744,2
2,120507,ICICI Pru Liquid Fund - Regular - Growth,7.394286,29.0,1.0,3.0,6.0,1.0,28.205128,100.000000,94.871795,87.179487,100.000000,75.512821,3
3,120504,ICICI Pru Bluechip Fund - Direct - Growth,32.487429,3.0,8.0,27.0,11.0,12.0,94.871795,82.051282,33.333333,74.358974,71.794872,73.974359,4
4,100025,HDFC Short Term Debt Fund - Regular - Growth,3.916390,34.0,4.0,1.0,2.0,4.0,15.384615,92.307692,100.000000,97.435897,92.307692,71.538462,5

In [4]:
tracking_error = pd.read_csv(
    "tracking_error_comparison.csv"
)

benchmark_summary = pd.read_csv(
    "benchmark_summary.csv"
)

rolling_tracking = pd.read_csv(
    "rolling_30d_tracking_difference.csv"
)

normalized = pd.read_csv(
    "normalized_benchmark_performance.csv"
)

print("Tracking Error:", tracking_error.shape)
print("Benchmark Summary:", benchmark_summary.shape)
print("Rolling Tracking:", rolling_tracking.shape)
print("Normalized Performance:", normalized.shape)

Tracking Error: (5, 6)
Benchmark Summary: (5, 8)
Rolling Tracking: (11500, 5)
Normalized Performance: (8050, 5)

In [5]:
print("\nTracking Error columns:")
print(tracking_error.columns.tolist())

print("\nBenchmarks:")
print(
    tracking_error[
        [
            "Tracking_Error_NIFTY50_pct",
            "Tracking_Error_NIFTY100_pct"
        ]
    ].describe()
)

Tracking Error columns:
['amfi_code', 'scheme_name', 'Tracking_Error_NIFTY50_pct', 'Tracking_Error_NIFTY100_pct', 'Observations_NIFTY50', 'Observations_NIFTY100']

Benchmarks:
       Tracking_Error_NIFTY50_pct  Tracking_Error_NIFTY100_pct
count                    5.000000                     5.000000
mean                    17.117538                    17.025087
std                      3.562060                     3.575719
min                     12.891203                    12.904358
25%                     13.644549                    13.453514
50%                     19.137582                    18.966368
75%                     19.399579                    19.158700
max                     20.514777                    20.642497

In [6]:
#Check top 5
top5_final = (
    scorecard
    .sort_values("Overall_Rank")
    .head(5)
)

display(
    top5_final[
        [
            "Overall_Rank",
            "scheme_name",
            "CAGR_3Y_pct",
            "Fund_Score"
        ]
    ]
)

,Overall_Rank,scheme_name,CAGR_3Y_pct,Fund_Score
0,1,Mirae Asset Large Cap Fund - Regular - Growth,34.000916,81.666667
1,2,Kotak Flexicap Fund - Regular - Growth,29.582770,78.589744
2,3,ICICI Pru Liquid Fund - Regular - Growth,7.394286,75.512821
3,4,ICICI Pru Bluechip Fund - Direct - Growth,32.487429,73.974359
4,5,HDFC Short Term Debt Fund - Regular - Growth,3.916390,71.538462

In [7]:
# ============================================================
# CELL 3 — FUND SCORECARD VALIDATION
# ============================================================

scorecard = pd.read_csv("fund_scorecard.csv")

print("=" * 60)
print("FUND SCORECARD VALIDATION")
print("=" * 60)

# 1. Shape
print("\n1. Scorecard Shape:")
print(scorecard.shape)

# 2. Columns
print("\n2. Columns:")
print(scorecard.columns.tolist())

# 3. Duplicate AMFI codes
print("\n3. Duplicate AMFI Codes:")
print(scorecard["amfi_code"].duplicated().sum())

# 4. Missing values
print("\n4. Missing Values:")
display(scorecard.isna().sum())

# 5. Check old return column
print("\n5. Old Return Column Check:")

if "return_3yr_pct" in scorecard.columns:
    print("⚠️ OLD return_3yr_pct COLUMN FOUND")
else:
    print("✅ return_3yr_pct not found")

# 6. Check CAGR
print("\n6. CAGR Check:")

if "CAGR_3Y_pct" in scorecard.columns:
    print("✅ CAGR_3Y_pct exists")
    print(scorecard["CAGR_3Y_pct"].describe())
else:
    print("❌ CAGR_3Y_pct missing")

# 7. Fund Score range
print("\n7. Fund Score Range:")
print(
    "Minimum:",
    scorecard["Fund_Score"].min()
)

print(
    "Maximum:",
    scorecard["Fund_Score"].max()
)

# 8. Duplicate scheme names
print("\n8. Duplicate Scheme Names:")
print(
    scorecard["scheme_name"].duplicated().sum()
)

# 9. Top 10 funds
print("\n9. TOP 10 FUNDS:")
display(
    scorecard
    .sort_values("Overall_Rank")
    [
        [
            "Overall_Rank",
            "scheme_name",
            "CAGR_3Y_pct",
            "Fund_Score"
        ]
    ]
    .head(10)
)

print("\n" + "=" * 60)
print("SCORECARD VALIDATION COMPLETE")
print("=" * 60)

============================================================
FUND SCORECARD VALIDATION
============================================================

1. Scorecard Shape:
(40, 15)

2. Columns:
['amfi_code', 'scheme_name', 'CAGR_3Y_pct', 'Return_Rank', 'Sharpe_Rank', 'Alpha_Rank', 'Expense_Rank', 'MDD_Rank', 'Return_Score', 'Sharpe_Score', 'Alpha_Score', 'Expense_Score', 'MDD_Score', 'Fund_Score', 'Overall_Rank']

3. Duplicate AMFI Codes:
0

4. Missing Values:

amfi_code        0
scheme_name      0
CAGR_3Y_pct      0
Return_Rank      0
Sharpe_Rank      0
Alpha_Rank       0
Expense_Rank     0
MDD_Rank         0
Return_Score     0
Sharpe_Score     0
Alpha_Score      0
Expense_Score    0
MDD_Score        0
Fund_Score       0
Overall_Rank     0
dtype: int64

5. Old Return Column Check:
✅ return_3yr_pct not found

6. CAGR Check:
✅ CAGR_3Y_pct exists
count    40.000000
mean     16.414715
std      12.206752
min     -11.705807
25%       6.600925
50%      18.233102
75%      26.902600
max      35.111802
Name: CAGR_3Y_pct, dtype: float64

7. Fund Score Range:
Minimum: 24.102564102564106
Maximum: 81.66666666666667

8. Duplicate Scheme Names:
0

9. TOP 10 FUNDS:

,Overall_Rank,scheme_name,CAGR_3Y_pct,Fund_Score
0,1,Mirae Asset Large Cap Fund - Regular - Growth,34.000916,81.666667
1,2,Kotak Flexicap Fund - Regular - Growth,29.582770,78.589744
2,3,ICICI Pru Liquid Fund - Regular - Growth,7.394286,75.512821
3,4,ICICI Pru Bluechip Fund - Direct - Growth,32.487429,73.974359
4,5,HDFC Short Term Debt Fund - Regular - Growth,3.916390,71.538462
5,6,Kotak Liquid Fund - Regular - Growth,6.695972,70.384615
6,7,Nippon India ETF Nifty 50 BeES,20.008208,68.974359
7,8,ABSL Frontline Equity Fund - Regular - Growth,28.967695,67.564103
8,9,Axis Midcap Fund - Regular - Growth,35.111802,66.282051
9,10,Nippon India Large Cap Fund - Direct - Growth,21.089977,66.282051

============================================================
SCORECARD VALIDATION COMPLETE
============================================================

In [8]:
# Continue Scorecard QA

print("\n4. Missing Values:")
display(scorecard.isna().sum())

print("\n5. Old Return Column Check:")
print("return_3yr_pct exists:",
      "return_3yr_pct" in scorecard.columns)

print("\n6. CAGR Statistics:")
display(scorecard["CAGR_3Y_pct"].describe())

print("\n7. Fund Score Statistics:")
display(scorecard["Fund_Score"].describe())

print("\n8. Top 10 Funds:")
display(
    scorecard
    .sort_values("Overall_Rank")
    [
        [
            "Overall_Rank",
            "scheme_name",
            "CAGR_3Y_pct",
            "Fund_Score"
        ]
    ]
    .head(10)
)

4. Missing Values:

amfi_code        0
scheme_name      0
CAGR_3Y_pct      0
Return_Rank      0
Sharpe_Rank      0
Alpha_Rank       0
Expense_Rank     0
MDD_Rank         0
Return_Score     0
Sharpe_Score     0
Alpha_Score      0
Expense_Score    0
MDD_Score        0
Fund_Score       0
Overall_Rank     0
dtype: int64

5. Old Return Column Check:
return_3yr_pct exists: False

6. CAGR Statistics:

count    40.000000
mean     16.414715
std      12.206752
min     -11.705807
25%       6.600925
50%      18.233102
75%      26.902600
max      35.111802
Name: CAGR_3Y_pct, dtype: float64

7. Fund Score Statistics:

count    40.000000
mean     56.589744
std      13.465523
min      24.102564
25%      46.185897
50%      59.038462
75%      65.993590
max      81.666667
Name: Fund_Score, dtype: float64

8. Top 10 Funds:

,Overall_Rank,scheme_name,CAGR_3Y_pct,Fund_Score
0,1,Mirae Asset Large Cap Fund - Regular - Growth,34.000916,81.666667
1,2,Kotak Flexicap Fund - Regular - Growth,29.582770,78.589744
2,3,ICICI Pru Liquid Fund - Regular - Growth,7.394286,75.512821
3,4,ICICI Pru Bluechip Fund - Direct - Growth,32.487429,73.974359
4,5,HDFC Short Term Debt Fund - Regular - Growth,3.916390,71.538462
5,6,Kotak Liquid Fund - Regular - Growth,6.695972,70.384615
6,7,Nippon India ETF Nifty 50 BeES,20.008208,68.974359
7,8,ABSL Frontline Equity Fund - Regular - Growth,28.967695,67.564103
8,9,Axis Midcap Fund - Regular - Growth,35.111802,66.282051
9,10,Nippon India Large Cap Fund - Direct - Growth,21.089977,66.282051

In [9]:
# ============================================================
# CELL 4 — BENCHMARK & TRACKING ERROR VALIDATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 60)
print("BENCHMARK & TRACKING ERROR VALIDATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Load benchmark outputs
# ------------------------------------------------------------

tracking_error = pd.read_csv(
    "tracking_error_comparison.csv"
)

benchmark_summary = pd.read_csv(
    "benchmark_summary.csv"
)

rolling_tracking = pd.read_csv(
    "rolling_30d_tracking_difference.csv"
)

normalized = pd.read_csv(
    "normalized_benchmark_performance.csv"
)

# ------------------------------------------------------------
# 2. Display shapes
# ------------------------------------------------------------

print("\n1. Dataset Shapes")

print(
    "Tracking Error:",
    tracking_error.shape
)

print(
    "Benchmark Summary:",
    benchmark_summary.shape
)

print(
    "Rolling Tracking Difference:",
    rolling_tracking.shape
)

print(
    "Normalized Performance:",
    normalized.shape
)

# ------------------------------------------------------------
# 3. Tracking Error columns
# ------------------------------------------------------------

print("\n2. Tracking Error Columns")

print(
    tracking_error.columns.tolist()
)

# ------------------------------------------------------------
# 4. Check NIFTY50 Tracking Error
# ------------------------------------------------------------

print("\n3. NIFTY50 Tracking Error")

if "Tracking_Error_NIFTY50_pct" in tracking_error.columns:

    print("✅ NIFTY50 Tracking Error exists")

    print(
        tracking_error[
            "Tracking_Error_NIFTY50_pct"
        ].describe()
    )

else:

    print(
        "❌ NIFTY50 Tracking Error missing"
    )

# ------------------------------------------------------------
# 5. Check NIFTY100 Tracking Error
# ------------------------------------------------------------

print("\n4. NIFTY100 Tracking Error")

if "Tracking_Error_NIFTY100_pct" in tracking_error.columns:

    print("✅ NIFTY100 Tracking Error exists")

    print(
        tracking_error[
            "Tracking_Error_NIFTY100_pct"
        ].describe()
    )

else:

    print(
        "❌ NIFTY100 Tracking Error missing"
    )

# ------------------------------------------------------------
# 6. Check missing values
# ------------------------------------------------------------

print("\n5. Tracking Error Missing Values")

display(
    tracking_error.isna().sum()
)

# ------------------------------------------------------------
# 7. Check Top 5 funds
# ------------------------------------------------------------

print("\n6. Tracking Error Fund Count")

print(
    "Number of funds:",
    tracking_error["scheme_name"].nunique()
)

print("\nFunds:")

display(
    tracking_error[
        [
            "scheme_name",
            "Tracking_Error_NIFTY50_pct",
            "Tracking_Error_NIFTY100_pct"
        ]
    ]
)

# ------------------------------------------------------------
# 8. Check rolling tracking difference
# ------------------------------------------------------------

print("\n7. Rolling Tracking Difference")

print(
    "Benchmarks:",
    rolling_tracking["Benchmark"].unique()
)

print(
    "Funds:",
    rolling_tracking["scheme_name"].nunique()
)

print(
    "Rows:",
    len(rolling_tracking)
)

print("\nMissing values:")

display(
    rolling_tracking.isna().sum()
)

# ------------------------------------------------------------
# 9. Check normalized performance
# ------------------------------------------------------------

print("\n8. Normalized Performance")

print(
    "Series:",
    normalized["Series"].unique()
)

print(
    "Number of series:",
    normalized["Series"].nunique()
)

print(
    "Date range:",
    normalized["date"].min(),
    "to",
    normalized["date"].max()
)

# ------------------------------------------------------------
# 10. Final benchmark QA
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("BENCHMARK QA SUMMARY")
print("=" * 60)

checks = {
    "Tracking Error vs NIFTY50":
        "Tracking_Error_NIFTY50_pct"
        in tracking_error.columns,

    "Tracking Error vs NIFTY100":
        "Tracking_Error_NIFTY100_pct"
        in tracking_error.columns,

    "Top 5 funds":
        tracking_error["scheme_name"].nunique() == 5,

    "NIFTY50 benchmark":
        "NIFTY50"
        in rolling_tracking["Benchmark"].unique(),

    "NIFTY100 benchmark":
        "NIFTY100"
        in rolling_tracking["Benchmark"].unique(),

    "Normalized performance":
        len(normalized) > 0
}

for check, result in checks.items():

    if result:
        print(f"✅ {check}")

    else:
        print(f"❌ {check}")

print("=" * 60)

============================================================
BENCHMARK & TRACKING ERROR VALIDATION
============================================================

1. Dataset Shapes
Tracking Error: (5, 6)
Benchmark Summary: (5, 8)
Rolling Tracking Difference: (11500, 5)
Normalized Performance: (8050, 5)

2. Tracking Error Columns
['amfi_code', 'scheme_name', 'Tracking_Error_NIFTY50_pct', 'Tracking_Error_NIFTY100_pct', 'Observations_NIFTY50', 'Observations_NIFTY100']

3. NIFTY50 Tracking Error
✅ NIFTY50 Tracking Error exists
count     5.000000
mean     17.117538
std       3.562060
min      12.891203
25%      13.644549
50%      19.137582
75%      19.399579
max      20.514777
Name: Tracking_Error_NIFTY50_pct, dtype: float64

4. NIFTY100 Tracking Error
✅ NIFTY100 Tracking Error exists
count     5.000000
mean     17.025087
std       3.575719
min      12.904358
25%      13.453514
50%      18.966368
75%      19.158700
max      20.642497
Name: Tracking_Error_NIFTY100_pct, dtype: float64

5. Tracking Error Missing Values

amfi_code                      0
scheme_name                    0
Tracking_Error_NIFTY50_pct     0
Tracking_Error_NIFTY100_pct    0
Observations_NIFTY50           0
Observations_NIFTY100          0
dtype: int64

6. Tracking Error Fund Count
Number of funds: 5

Funds:

,scheme_name,Tracking_Error_NIFTY50_pct,Tracking_Error_NIFTY100_pct
0,ICICI Pru Liquid Fund - Regular - Growth,12.891203,12.904358
1,HDFC Short Term Debt Fund - Regular - Growth,13.644549,13.453514
2,ICICI Pru Bluechip Fund - Direct - Growth,19.137582,19.158700
3,Mirae Asset Large Cap Fund - Regular - Growth,19.399579,18.966368
4,Kotak Flexicap Fund - Regular - Growth,20.514777,20.642497

7. Rolling Tracking Difference
Benchmarks: ['NIFTY50' 'NIFTY100']
Funds: 5
Rows: 11500

Missing values:

date                                     0
amfi_code                                0
scheme_name                              0
Benchmark                                0
Rolling_30D_Tracking_Difference_pct    200
dtype: int64

8. Normalized Performance
Series: ['HDFC Short Term Debt Fund - Regular - Growth'
 'ICICI Pru Bluechip Fund - Direct - Growth'
 'ICICI Pru Liquid Fund - Regular - Growth'
 'Kotak Flexicap Fund - Regular - Growth'
 'Mirae Asset Large Cap Fund - Regular - Growth' 'NIFTY50' 'NIFTY100']
Number of series: 7
Date range: 2022-01-03 to 2026-05-29

============================================================
BENCHMARK QA SUMMARY
============================================================
✅ Tracking Error vs NIFTY50
✅ Tracking Error vs NIFTY100
✅ Top 5 funds
✅ NIFTY50 benchmark
✅ NIFTY100 benchmark
✅ Normalized performance
============================================================

In [10]:
# ============================================================
# CELL 5 — NORMALIZED PERFORMANCE VALIDATION
# ============================================================

print("=" * 60)
print("NORMALIZED PERFORMANCE VALIDATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Basic information
# ------------------------------------------------------------

print("\n1. Dataset Information")

print("Shape:", normalized.shape)

print("Date range:")
print(
    normalized["date"].min(),
    "to",
    normalized["date"].max()
)

print(
    "Number of unique series:",
    normalized["Series"].nunique()
)

print("\nSeries:")
print(
    normalized["Series"].unique()
)

# ------------------------------------------------------------
# 2. Check starting value
# ------------------------------------------------------------

print("\n2. Starting Values")

first_date = normalized["date"].min()

starting_values = (
    normalized[
        normalized["date"] == first_date
    ]
    [
        ["Series", "Normalized_Value"]
    ]
)

display(starting_values)

# ------------------------------------------------------------
# 3. Check for invalid normalized values
# ------------------------------------------------------------

print("\n3. Invalid Values")

print(
    "Negative normalized values:",
    (
        normalized["Normalized_Value"] < 0
    ).sum()
)

print(
    "Missing normalized values:",
    normalized["Normalized_Value"].isna().sum()
)

print(
    "Infinite values:",
    np.isinf(
        normalized["Normalized_Value"]
    ).sum()
)

# ------------------------------------------------------------
# 4. Performance summary
# ------------------------------------------------------------

print("\n4. Final Performance")

performance_check = []

for series in normalized["Series"].unique():

    temp = normalized[
        normalized["Series"] == series
    ].sort_values("date")

    start_value = temp[
        "Normalized_Value"
    ].iloc[0]

    final_value = temp[
        "Normalized_Value"
    ].iloc[-1]

    total_return = (
        (final_value / start_value) - 1
    ) * 100

    performance_check.append({
        "Series": series,
        "Start_Value": start_value,
        "Final_Value": final_value,
        "Total_Return_pct": total_return
    })

performance_check = pd.DataFrame(
    performance_check
).sort_values(
    "Total_Return_pct",
    ascending=False
)

display(performance_check)

# ------------------------------------------------------------
# 5. Check benchmarks
# ------------------------------------------------------------

print("\n5. Benchmark Check")

required_benchmarks = [
    "NIFTY50",
    "NIFTY100"
]

for benchmark in required_benchmarks:

    if benchmark in normalized["Series"].unique():
        print(f"✅ {benchmark} present")
    else:
        print(f"❌ {benchmark} missing")

# ------------------------------------------------------------
# 6. Final normalized QA
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("NORMALIZED PERFORMANCE QA SUMMARY")
print("=" * 60)

checks = {
    "Dataset contains data":
        len(normalized) > 0,

    "NIFTY50 present":
        "NIFTY50" in normalized["Series"].unique(),

    "NIFTY100 present":
        "NIFTY100" in normalized["Series"].unique(),

    "No negative normalized values":
        (normalized["Normalized_Value"] < 0).sum() == 0,

    "No missing normalized values":
        normalized["Normalized_Value"].isna().sum() == 0,

    "No infinite values":
        np.isinf(
            normalized["Normalized_Value"]
        ).sum() == 0
}

for check, result in checks.items():

    if result:
        print(f"✅ {check}")
    else:
        print(f"❌ {check}")

print("=" * 60)

============================================================
NORMALIZED PERFORMANCE VALIDATION
============================================================

1. Dataset Information
Shape: (8050, 5)
Date range:
2022-01-03 to 2026-05-29
Number of unique series: 7

Series:
['HDFC Short Term Debt Fund - Regular - Growth'
 'ICICI Pru Bluechip Fund - Direct - Growth'
 'ICICI Pru Liquid Fund - Regular - Growth'
 'Kotak Flexicap Fund - Regular - Growth'
 'Mirae Asset Large Cap Fund - Regular - Growth' 'NIFTY50' 'NIFTY100']

2. Starting Values

                                             Series  Normalized_Value
0      HDFC Short Term Debt Fund - Regular - Growth             100.0
1150      ICICI Pru Bluechip Fund - Direct - Growth             100.0
2300       ICICI Pru Liquid Fund - Regular - Growth             100.0
3450         Kotak Flexicap Fund - Regular - Growth             100.0
4600  Mirae Asset Large Cap Fund - Regular - Growth             100.0
5750                                        NIFTY50             100.0
6900                                       NIFTY100             100.0

3. Invalid Values
Negative normalized values: 0
Missing normalized values: 0
Infinite values: 0

4. Final Performance

,Series,Start_Value,Final_Value,Total_Return_pct
4,Mirae Asset Large Cap Fund - Regular - Growth,100.0,327.781083,227.781083
3,Kotak Flexicap Fund - Regular - Growth,100.0,327.047809,227.047809
1,ICICI Pru Bluechip Fund - Direct - Growth,100.0,251.267885,151.267885
2,ICICI Pru Liquid Fund - Regular - Growth,100.0,135.993389,35.993389
0,HDFC Short Term Debt Fund - Regular - Growth,100.0,121.155227,21.155227
6,NIFTY100,100.0,110.788751,10.788751
5,NIFTY50,100.0,105.858757,5.858757

5. Benchmark Check
✅ NIFTY50 present
✅ NIFTY100 present

============================================================
NORMALIZED PERFORMANCE QA SUMMARY
============================================================
✅ Dataset contains data
✅ NIFTY50 present
✅ NIFTY100 present
✅ No negative normalized values
✅ No missing normalized values
✅ No infinite values
============================================================

In [11]:
# ============================================================
# CELL 6 — FINAL PROJECT CONSISTENCY CHECK
# ============================================================

print("=" * 70)
print("FINAL PROJECT CONSISTENCY CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Get Top 5 from final scorecard
# ------------------------------------------------------------

top5_scorecard = (
    scorecard
    .sort_values("Overall_Rank")
    .head(5)
    [["amfi_code", "scheme_name", "Overall_Rank"]]
    .copy()
)

print("\n1. TOP 5 FUNDS FROM FINAL SCORECARD")
display(top5_scorecard)

# ------------------------------------------------------------
# 2. Get funds from Tracking Error
# ------------------------------------------------------------

te_funds = set(
    tracking_error["scheme_name"]
    .dropna()
    .astype(str)
)

# ------------------------------------------------------------
# 3. Get funds from Rolling Tracking Difference
# ------------------------------------------------------------

rolling_funds = set(
    rolling_tracking["scheme_name"]
    .dropna()
    .astype(str)
)

# ------------------------------------------------------------
# 4. Get funds from normalized performance
# ------------------------------------------------------------

benchmark_names = {
    "NIFTY50",
    "NIFTY100"
}

normalized_funds = set(
    normalized["Series"]
    .dropna()
    .astype(str)
) - benchmark_names

# ------------------------------------------------------------
# 5. Scorecard Top 5 set
# ------------------------------------------------------------

scorecard_funds = set(
    top5_scorecard["scheme_name"]
    .astype(str)
)

# ------------------------------------------------------------
# 6. Compare all datasets
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TOP 5 CONSISTENCY")
print("=" * 70)

print(
    "Scorecard Top 5:",
    len(scorecard_funds)
)

print(
    "Tracking Error funds:",
    len(te_funds)
)

print(
    "Rolling Tracking funds:",
    len(rolling_funds)
)

print(
    "Normalized Performance funds:",
    len(normalized_funds)
)

# ------------------------------------------------------------
# 7. Compare Scorecard vs Tracking Error
# ------------------------------------------------------------

print("\n2. SCORECARD vs TRACKING ERROR")

missing_from_te = (
    scorecard_funds - te_funds
)

extra_in_te = (
    te_funds - scorecard_funds
)

if not missing_from_te and not extra_in_te:

    print(
        "✅ Top 5 funds match Tracking Error dataset"
    )

else:

    print(
        "⚠️ Difference detected"
    )

    if missing_from_te:
        print(
            "Missing from Tracking Error:"
        )
        print(missing_from_te)

    if extra_in_te:
        print(
            "Extra funds in Tracking Error:"
        )
        print(extra_in_te)

# ------------------------------------------------------------
# 8. Compare Scorecard vs Rolling Tracking
# ------------------------------------------------------------

print("\n3. SCORECARD vs ROLLING TRACKING")

missing_from_rolling = (
    scorecard_funds - rolling_funds
)

extra_in_rolling = (
    rolling_funds - scorecard_funds
)

if not missing_from_rolling and not extra_in_rolling:

    print(
        "✅ Top 5 funds match Rolling Tracking dataset"
    )

else:

    print(
        "⚠️ Difference detected"
    )

    if missing_from_rolling:
        print(
            "Missing from Rolling Tracking:"
        )
        print(missing_from_rolling)

    if extra_in_rolling:
        print(
            "Extra funds in Rolling Tracking:"
        )
        print(extra_in_rolling)

# ------------------------------------------------------------
# 9. Compare Scorecard vs Normalized Performance
# ------------------------------------------------------------

print("\n4. SCORECARD vs NORMALIZED PERFORMANCE")

missing_from_normalized = (
    scorecard_funds - normalized_funds
)

extra_in_normalized = (
    normalized_funds - scorecard_funds
)

if not missing_from_normalized and not extra_in_normalized:

    print(
        "✅ Top 5 funds match Normalized Performance dataset"
    )

else:

    print(
        "⚠️ Difference detected"
    )

    if missing_from_normalized:
        print(
            "Missing from Normalized Performance:"
        )
        print(missing_from_normalized)

    if extra_in_normalized:
        print(
            "Extra funds in Normalized Performance:"
        )
        print(extra_in_normalized)

# ------------------------------------------------------------
# 10. Benchmark consistency
# ------------------------------------------------------------

print("\n5. BENCHMARK CONSISTENCY")

required_benchmarks = {
    "NIFTY50",
    "NIFTY100"
}

rolling_benchmarks = set(
    rolling_tracking["Benchmark"]
    .dropna()
    .astype(str)
)

normalized_benchmarks = set(
    normalized["Series"]
    .dropna()
    .astype(str)
) & required_benchmarks

print(
    "Rolling Tracking benchmarks:",
    rolling_benchmarks
)

print(
    "Normalized benchmarks:",
    normalized_benchmarks
)

if required_benchmarks.issubset(
    rolling_benchmarks
):

    print(
        "✅ Rolling Tracking contains both benchmarks"
    )

else:

    print(
        "❌ Rolling Tracking benchmark issue"
    )

if required_benchmarks.issubset(
    normalized_benchmarks
):

    print(
        "✅ Normalized Performance contains both benchmarks"
    )

else:

    print(
        "❌ Normalized Performance benchmark issue"
    )

# ------------------------------------------------------------
# 11. Final QA result
# ------------------------------------------------------------

all_consistent = (
    scorecard_funds == te_funds
    and
    scorecard_funds == rolling_funds
    and
    scorecard_funds == normalized_funds
    and
    required_benchmarks.issubset(
        rolling_benchmarks
    )
    and
    required_benchmarks.issubset(
        normalized_benchmarks
    )
)

print("\n" + "=" * 70)
print("FINAL CONSISTENCY RESULT")
print("=" * 70)

if all_consistent:

    print(
        "🎉 PASS — All Top 5 funds and benchmarks "
        "are consistent across the project."
    )

else:

    print(
        "⚠️ REVIEW REQUIRED — Some datasets are not consistent."
    )

print("=" * 70)

======================================================================
FINAL PROJECT CONSISTENCY CHECK
======================================================================

1. TOP 5 FUNDS FROM FINAL SCORECARD

   amfi_code                                    scheme_name  Overall_Rank
0     148567  Mirae Asset Large Cap Fund - Regular - Growth             1
1     120843         Kotak Flexicap Fund - Regular - Growth             2
2     120507       ICICI Pru Liquid Fund - Regular - Growth             3
3     120504      ICICI Pru Bluechip Fund - Direct - Growth             4
4     100025   HDFC Short Term Debt Fund - Regular - Growth             5

======================================================================
TOP 5 CONSISTENCY
======================================================================
Scorecard Top 5: 5
Tracking Error funds: 5
Rolling Tracking funds: 5
Normalized Performance funds: 5

2. SCORECARD vs TRACKING ERROR
✅ Top 5 funds match Tracking Error dataset

3. SCORECARD vs ROLLING TRACKING
✅ Top 5 funds match Rolling Tracking dataset

4. SCORECARD vs NORMALIZED PERFORMANCE
✅ Top 5 funds match Normalized Performance dataset

5. BENCHMARK CONSISTENCY
Rolling Tracking benchmarks: {'NIFTY50', 'NIFTY100'}
Normalized benchmarks: {'NIFTY50', 'NIFTY100'}
✅ Rolling Tracking contains both benchmarks
✅ Normalized Performance contains both benchmarks

======================================================================
FINAL CONSISTENCY RESULT
======================================================================
🎉 PASS — All Top 5 funds and benchmarks are consistent across the project.
======================================================================

In [12]:
# ============================================================
# CELL 7 — FINAL PROJECT SUMMARY & SUBMISSION CHECKLIST
# ============================================================

import os

print("=" * 70)
print("MUTUAL FUND ANALYTICS — FINAL SUBMISSION CHECK")
print("=" * 70)

# ------------------------------------------------------------
# Required analytical outputs
# ------------------------------------------------------------

required_outputs = {
    "Fund Scorecard":
        "fund_scorecard.csv",

    "Tracking Error Comparison":
        "tracking_error_comparison.csv",

    "Benchmark Summary":
        "benchmark_summary.csv",

    "Rolling 30-Day Tracking Difference":
        "rolling_30d_tracking_difference.csv",

    "Normalized Benchmark Performance":
        "normalized_benchmark_performance.csv",

    "Normalized Performance Chart":
        "normalized_benchmark_performance.png",

    "Rolling 30D NIFTY50 Chart":
        "rolling_30d_tracking_difference_nifty50.png",

    "Rolling 30D NIFTY100 Chart":
        "rolling_30d_tracking_difference_nifty100.png"
}

print("\n1. REQUIRED OUTPUT FILES")
print("-" * 70)

passed_files = 0

for name, path in required_outputs.items():

    if os.path.exists(path):

        print(f"✅ {name}")
        passed_files += 1

    else:

        print(f"❌ {name}")

print(
    f"\nFiles available: "
    f"{passed_files}/{len(required_outputs)}"
)

# ------------------------------------------------------------
# Core analytical checks
# ------------------------------------------------------------

print("\n2. CORE ANALYTICAL CHECKS")
print("-" * 70)

checks = {}

checks["40 funds in scorecard"] = (
    len(scorecard) == 40
)

checks["No duplicate AMFI codes"] = (
    scorecard["amfi_code"].duplicated().sum() == 0
)

checks["CAGR available"] = (
    "CAGR_3Y_pct" in scorecard.columns
)

checks["Fund Score available"] = (
    "Fund_Score" in scorecard.columns
)

checks["Overall Rank available"] = (
    "Overall_Rank" in scorecard.columns
)

checks["NIFTY50 Tracking Error"] = (
    "Tracking_Error_NIFTY50_pct"
    in tracking_error.columns
)

checks["NIFTY100 Tracking Error"] = (
    "Tracking_Error_NIFTY100_pct"
    in tracking_error.columns
)

checks["Top 5 funds"] = (
    tracking_error["scheme_name"].nunique() == 5
)

checks["NIFTY50 benchmark"] = (
    "NIFTY50"
    in rolling_tracking["Benchmark"].unique()
)

checks["NIFTY100 benchmark"] = (
    "NIFTY100"
    in rolling_tracking["Benchmark"].unique()
)

for check, result in checks.items():

    if result:
        print(f"✅ {check}")
    else:
        print(f"❌ {check}")

# ------------------------------------------------------------
# Final result
# ------------------------------------------------------------

all_files_available = (
    passed_files == len(required_outputs)
)

all_checks_passed = all(checks.values())

print("\n" + "=" * 70)
print("FINAL RESULT")
print("=" * 70)

if all_files_available and all_checks_passed:

    print(
        "🎉 PROJECT ANALYTICAL QA PASSED"
    )

    print(
        "\nYour Python analytical pipeline is "
        "ready for final documentation/submission."
    )

else:

    print(
        "⚠️ PROJECT QA REQUIRES REVIEW"
    )

    print(
        "\nFix the ❌ items before final submission."
    )

print("=" * 70)

======================================================================
MUTUAL FUND ANALYTICS — FINAL SUBMISSION CHECK
======================================================================

1. REQUIRED OUTPUT FILES
----------------------------------------------------------------------
✅ Fund Scorecard
✅ Tracking Error Comparison
✅ Benchmark Summary
✅ Rolling 30-Day Tracking Difference
✅ Normalized Benchmark Performance
✅ Normalized Performance Chart
✅ Rolling 30D NIFTY50 Chart
✅ Rolling 30D NIFTY100 Chart

Files available: 8/8

2. CORE ANALYTICAL CHECKS
----------------------------------------------------------------------
✅ 40 funds in scorecard
✅ No duplicate AMFI codes
✅ CAGR available
✅ Fund Score available
✅ Overall Rank available
✅ NIFTY50 Tracking Error
✅ NIFTY100 Tracking Error
✅ Top 5 funds
✅ NIFTY50 benchmark
✅ NIFTY100 benchmark

======================================================================
FINAL RESULT
======================================================================
🎉 PROJECT ANALYTICAL QA PASSED

Your Python analytical pipeline is ready for final documentation/submission.
======================================================================